# Workflow name
name: Go CI

# Triggers: Run on push or pull request to main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Environment variables for reusability
env:
  GO_VERSION: '1.23' # Adjust to your project's Go version

# Jobs to execute
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true # Cache Go modules for faster builds

      # Verify and tidy dependencies
      - name: Get Dependencies
        run: go mod tidy && go mod verify

      # # Run linting with golangci-lint (optional)
      # - name: Lint
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     version: latest
      #     args: --timeout=3m

      # # Run tests with coverage
      # - name: Test
      #   run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

      # Build the project
      - name: Build
        run: go build -v ./...

      # Optional: Upload coverage report to Codecov
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }} # Requires a secret in your repo
